// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP2.Data;

#nullable disable

namespace TP2.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20250304164856_ReservationsMigration")]
    partial class ReservationsMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TP2.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 11, 29, 19, 4, 33, 702, DateTimeKind.Unspecified).AddTicks(544), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Annabelle_Bernier@hotmail.com",
                            FirstName = "Annabelle",
                            LastName = "Bernier"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 6, 21, 16, 38, 29, 953, DateTimeKind.Unspecified).AddTicks(454), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Cassidy.Rippin@gmail.com",
                            FirstName = "Cassidy",
                            LastName = "Rippin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 12, 12, 3, 54, 28, 41, DateTimeKind.Unspecified).AddTicks(6247), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Crystel.Aufderhar88@gmail.com",
                            FirstName = "Crystel",
                            LastName = "Aufderhar"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 8, 31, 10, 53, 27, 324, DateTimeKind.Unspecified).AddTicks(2698), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Flossie_Braun@yahoo.com",
                            FirstName = "Flossie",
                            LastName = "Braun"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 9, 4, 51, 18, 414, DateTimeKind.Unspecified).AddTicks(8402), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Liliane.Reynolds@hotmail.com",
                            FirstName = "Liliane",
                            LastName = "Reynolds"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 2, 1, 22, 39, 12, 250, DateTimeKind.Unspecified).AddTicks(5127), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Cortez77@yahoo.com",
                            FirstName = "Cortez",
                            LastName = "Larson"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 14, 14, 13, 40, 346, DateTimeKind.Unspecified).AddTicks(1811), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Jayson.King26@yahoo.com",
                            FirstName = "Jayson",
                            LastName = "King"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 23, 20, 0, 38, 131, DateTimeKind.Unspecified).AddTicks(8860), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Lorine.Grimes85@yahoo.com",
                            FirstName = "Lorine",
                            LastName = "Grimes"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 18, 8, 58, 37, 408, DateTimeKind.Unspecified).AddTicks(2281), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Levi53@yahoo.com",
                            FirstName = "Levi",
                            LastName = "Kiehn"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 6, 4, 9, 30, 7, 485, DateTimeKind.Unspecified).AddTicks(7662), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Annamae41@gmail.com",
                            FirstName = "Annamae",
                            LastName = "Waters"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 6, 13, 5, 51, 25, 25, DateTimeKind.Unspecified).AddTicks(9775), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Adriel_Schuppe76@gmail.com",
                            FirstName = "Adriel",
                            LastName = "Schuppe"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 19, 9, 38, 268, DateTimeKind.Unspecified).AddTicks(952), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Myrna_Rath@yahoo.com",
                            FirstName = "Myrna",
                            LastName = "Rath"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 12, 19, 0, 18, 12, 59, DateTimeKind.Unspecified).AddTicks(3356), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Destiny25@gmail.com",
                            FirstName = "Destiny",
                            LastName = "Blanda"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 2, 8, 15, 3, 54, 329, DateTimeKind.Unspecified).AddTicks(3517), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Kiana76@yahoo.com",
                            FirstName = "Kiana",
                            LastName = "Little"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 6, 23, 8, 14, 33, 976, DateTimeKind.Unspecified).AddTicks(9403), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Jackie_Rau27@gmail.com",
                            FirstName = "Jackie",
                            LastName = "Rau"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 7, 5, 14, 44, 38, 885, DateTimeKind.Unspecified).AddTicks(1255), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Eldora_Brown@gmail.com",
                            FirstName = "Eldora",
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 4, 5, 16, 35, 14, 602, DateTimeKind.Unspecified).AddTicks(4654), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Loyce93@hotmail.com",
                            FirstName = "Loyce",
                            LastName = "Bogan"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 30, 4, 2, 27, 597, DateTimeKind.Unspecified).AddTicks(4628), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Annalise63@yahoo.com",
                            FirstName = "Annalise",
                            LastName = "Stanton"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 11, 1, 4, 31, 1, 541, DateTimeKind.Unspecified).AddTicks(940), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Lukas_Walsh41@gmail.com",
                            FirstName = "Lukas",
                            LastName = "Walsh"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 11, 20, 20, 58, 4, 591, DateTimeKind.Unspecified).AddTicks(9707), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Demarcus30@gmail.com",
                            FirstName = "Demarcus",
                            LastName = "Stanton"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 2, 2, 16, 44, 7, 695, DateTimeKind.Unspecified).AddTicks(8928), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Carmel_Cummings@hotmail.com",
                            FirstName = "Carmel",
                            LastName = "Cummings"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 11, 5, 9, 9, 58, 721, DateTimeKind.Unspecified).AddTicks(8534), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Leora_Koch@hotmail.com",
                            FirstName = "Leora",
                            LastName = "Koch"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 7, 10, 8, 20, 38, 470, DateTimeKind.Unspecified).AddTicks(1153), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Hilma.Orn7@hotmail.com",
                            FirstName = "Hilma",
                            LastName = "Orn"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 7, 13, 20, 5, 28, 801, DateTimeKind.Unspecified).AddTicks(1605), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Henriette.Weimann@hotmail.com",
                            FirstName = "Henriette",
                            LastName = "Weimann"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 6, 13, 2, 13, 44, 131, DateTimeKind.Unspecified).AddTicks(6967), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Emerson_Spencer@hotmail.com",
                            FirstName = "Emerson",
                            LastName = "Spencer"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 7, 31, 9, 33, 3, 445, DateTimeKind.Unspecified).AddTicks(5844), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Alexandro.Lakin8@gmail.com",
                            FirstName = "Alexandro",
                            LastName = "Lakin"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 25, 20, 55, 3, 41, DateTimeKind.Unspecified).AddTicks(4366), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Rod_Goodwin@gmail.com",
                            FirstName = "Rod",
                            LastName = "Goodwin"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 5, 21, 40, 17, 249, DateTimeKind.Unspecified).AddTicks(4879), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Heber_Bogan54@yahoo.com",
                            FirstName = "Heber",
                            LastName = "Bogan"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 11, 22, 2, 52, 34, 51, DateTimeKind.Unspecified).AddTicks(4681), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Clinton.Morar82@hotmail.com",
                            FirstName = "Clinton",
                            LastName = "Morar"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 1, 22, 12, 2, 903, DateTimeKind.Unspecified).AddTicks(8879), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Susie.Fahey28@gmail.com",
                            FirstName = "Susie",
                            LastName = "Fahey"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 5, 8, 18, 14, 349, DateTimeKind.Unspecified).AddTicks(1106), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Nora_Funk61@gmail.com",
                            FirstName = "Nora",
                            LastName = "Funk"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 2, 12, 10, 20, 12, 724, DateTimeKind.Unspecified).AddTicks(9489), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Dayne.Cummerata@yahoo.com",
                            FirstName = "Dayne",
                            LastName = "Cummerata"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 11, 25, 17, 58, 37, 693, DateTimeKind.Unspecified).AddTicks(2547), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Nikita85@hotmail.com",
                            FirstName = "Nikita",
                            LastName = "Hettinger"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 8, 11, 8, 48, 16, 143, DateTimeKind.Unspecified).AddTicks(3618), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Stanton.Cummerata@yahoo.com",
                            FirstName = "Stanton",
                            LastName = "Cummerata"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 3, 17, 20, 14, 25, 844, DateTimeKind.Unspecified).AddTicks(1540), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Christopher.Gottlieb@yahoo.com",
                            FirstName = "Christopher",
                            LastName = "Gottlieb"
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 1, 6, 28, 0, 311, DateTimeKind.Unspecified).AddTicks(8784), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Isabella_Kutch@gmail.com",
                            FirstName = "Isabella",
                            LastName = "Kutch"
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 7, 14, 8, 23, 31, 866, DateTimeKind.Unspecified).AddTicks(2379), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Rubie95@hotmail.com",
                            FirstName = "Rubie",
                            LastName = "Wisozk"
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 11, 22, 3, 6, 201, DateTimeKind.Unspecified).AddTicks(2667), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Jayda.Koelpin54@gmail.com",
                            FirstName = "Jayda",
                            LastName = "Koelpin"
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 6, 6, 4, 29, 23, 226, DateTimeKind.Unspecified).AddTicks(7610), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Annie.Batz@gmail.com",
                            FirstName = "Annie",
                            LastName = "Batz"
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 18, 14, 27, 3, 235, DateTimeKind.Unspecified).AddTicks(4496), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Lizeth.Osinski8@yahoo.com",
                            FirstName = "Lizeth",
                            LastName = "Osinski"
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 3, 8, 12, 24, 2, 868, DateTimeKind.Unspecified).AddTicks(747), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Anabel_Gorczany@hotmail.com",
                            FirstName = "Anabel",
                            LastName = "Gorczany"
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 4, 17, 15, 16, 52, 644, DateTimeKind.Unspecified).AddTicks(8649), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Justine_Prosacco89@gmail.com",
                            FirstName = "Justine",
                            LastName = "Prosacco"
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 4, 24, 10, 50, 41, 913, DateTimeKind.Unspecified).AddTicks(8211), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Vivienne.Considine@hotmail.com",
                            FirstName = "Vivienne",
                            LastName = "Considine"
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 3, 14, 4, 56, 57, 754, DateTimeKind.Unspecified).AddTicks(4200), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Alvina17@gmail.com",
                            FirstName = "Alvina",
                            LastName = "Harvey"
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 10, 4, 0, 20, 893, DateTimeKind.Unspecified).AddTicks(3018), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Willy.Hahn@gmail.com",
                            FirstName = "Willy",
                            LastName = "Hahn"
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 8, 3, 17, 48, 35, 45, DateTimeKind.Unspecified).AddTicks(4671), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Laisha.Volkman@gmail.com",
                            FirstName = "Laisha",
                            LastName = "Volkman"
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 11, 30, 4, 4, 28, 170, DateTimeKind.Unspecified).AddTicks(8985), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Jimmie57@hotmail.com",
                            FirstName = "Jimmie",
                            LastName = "Shanahan"
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 7, 21, 48, 40, 203, DateTimeKind.Unspecified).AddTicks(1069), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Camille.Hudson48@yahoo.com",
                            FirstName = "Camille",
                            LastName = "Hudson"
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 2, 6, 19, 48, 19, 678, DateTimeKind.Unspecified).AddTicks(355), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Viva29@gmail.com",
                            FirstName = "Viva",
                            LastName = "Haag"
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 3, 18, 13, 30, 37, 251, DateTimeKind.Unspecified).AddTicks(8021), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Claire_Schaden32@yahoo.com",
                            FirstName = "Claire",
                            LastName = "Schaden"
                        });
                });

            modelBuilder.Entity("TP2.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Boisson",
                            Description = "Aut in itaque atque eveniet similique minima aperiam omnis non.",
                            IsAvailable = false,
                            Name = "Bière",
                            Price = 20.81197988350968800m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Boisson",
                            Description = "Quisquam saepe occaecati delectus voluptatum officiis doloremque autem sit quisquam.",
                            IsAvailable = false,
                            Name = "Boisson gazeuse",
                            Price = 21.05852739633459200m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Boisson",
                            Description = "Architecto provident explicabo quas doloribus et.",
                            IsAvailable = true,
                            Name = "Café",
                            Price = 9.88394521894582400m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Entrée",
                            Description = "Consequatur provident aut aliquam consequatur aut officiis pariatur id.",
                            IsAvailable = true,
                            Name = "Tartare de betteraves",
                            Price = 7.662214560989391200m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Entrée",
                            Description = "Pariatur velit et.",
                            IsAvailable = true,
                            Name = "Tartare de betteraves",
                            Price = 21.63894501103505600m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Boisson",
                            Description = "Voluptatem eos ea est quia.",
                            IsAvailable = true,
                            Name = "Boisson gazeuse",
                            Price = 23.38768144180889600m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Entrée",
                            Description = "Tempora rerum et et sunt omnis.",
                            IsAvailable = true,
                            Name = "Tartare de betteraves",
                            Price = 10.27535815900440800m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Entrée",
                            Description = "Non voluptas aut.",
                            IsAvailable = true,
                            Name = "Salade verte",
                            Price = 29.27488773819286400m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Plat principal",
                            Description = "Iusto dolorem perferendis porro distinctio numquam libero.",
                            IsAvailable = true,
                            Name = "Tataki de saumon",
                            Price = 9.32802476680745600m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Plat principal",
                            Description = "Molestiae ut repellendus nihil dolor et aliquid fuga.",
                            IsAvailable = true,
                            Name = "Aubergines farcies",
                            Price = 24.17132431161651200m
                        },
                        new
                        {
                            Id = 11,
                            Category = "Entrée",
                            Description = "Ut odit exercitationem occaecati velit est voluptatibus sed natus.",
                            IsAvailable = true,
                            Name = "Tartare de betteraves",
                            Price = 24.93670494783051200m
                        },
                        new
                        {
                            Id = 12,
                            Category = "Plat principal",
                            Description = "Veniam et voluptates in.",
                            IsAvailable = true,
                            Name = "Aubergines farcies",
                            Price = 11.16619491982097600m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Entrée",
                            Description = "Inventore blanditiis aspernatur sequi temporibus aut praesentium iure.",
                            IsAvailable = true,
                            Name = "Salade césar",
                            Price = 20.31585341405396000m
                        },
                        new
                        {
                            Id = 14,
                            Category = "Plat principal",
                            Description = "Quis sit ut.",
                            IsAvailable = true,
                            Name = "Bavette de boeuf",
                            Price = 27.91833901472777600m
                        },
                        new
                        {
                            Id = 15,
                            Category = "Boisson",
                            Description = "Et quia magnam aperiam et.",
                            IsAvailable = true,
                            Name = "Limonade",
                            Price = 10.27360098799858400m
                        },
                        new
                        {
                            Id = 16,
                            Category = "Entrée",
                            Description = "Quia laborum iusto labore veritatis ipsam similique.",
                            IsAvailable = true,
                            Name = "Salade césar",
                            Price = 21.57907213787969600m
                        },
                        new
                        {
                            Id = 17,
                            Category = "Dessert",
                            Description = "A aut vel quia sed culpa dolores quia dignissimos quam.",
                            IsAvailable = true,
                            Name = "Jell-O aux cerises",
                            Price = 8.382505665492502400m
                        },
                        new
                        {
                            Id = 18,
                            Category = "Plat principal",
                            Description = "Quia quisquam aliquam non id rerum quisquam nihil dolor.",
                            IsAvailable = true,
                            Name = "Burger de poulet",
                            Price = 19.35153169225973600m
                        },
                        new
                        {
                            Id = 19,
                            Category = "Entrée",
                            Description = "Culpa et assumenda esse deserunt magnam.",
                            IsAvailable = true,
                            Name = "Salade césar",
                            Price = 12.39441257059779200m
                        },
                        new
                        {
                            Id = 20,
                            Category = "Entrée",
                            Description = "Sequi aut explicabo temporibus eum ab nobis vel.",
                            IsAvailable = true,
                            Name = "Salade verte",
                            Price = 27.34875990491302400m
                        },
                        new
                        {
                            Id = 21,
                            Category = "Plat principal",
                            Description = "Magni sapiente labore corporis doloremque quas ea ipsam voluptates eos.",
                            IsAvailable = true,
                            Name = "Bavette de boeuf",
                            Price = 17.31135247593809600m
                        },
                        new
                        {
                            Id = 22,
                            Category = "Boisson",
                            Description = "Repellat animi eveniet eum quasi ut qui fugiat et sint.",
                            IsAvailable = false,
                            Name = "Lait",
                            Price = 6.389738360382495200m
                        },
                        new
                        {
                            Id = 23,
                            Category = "Dessert",
                            Description = "Perferendis odit enim.",
                            IsAvailable = true,
                            Name = "Gâteau au chocolat",
                            Price = 16.72101625346160800m
                        },
                        new
                        {
                            Id = 24,
                            Category = "Plat principal",
                            Description = "Adipisci iure omnis ex dolore dolore tempora doloribus vel architecto.",
                            IsAvailable = true,
                            Name = "Burger de poulet",
                            Price = 21.11372027296745600m
                        },
                        new
                        {
                            Id = 25,
                            Category = "Boisson",
                            Description = "Ut ut unde consequuntur laborum iure beatae debitis.",
                            IsAvailable = false,
                            Name = "Vin rouge",
                            Price = 26.90613534694356800m
                        },
                        new
                        {
                            Id = 26,
                            Category = "Boisson",
                            Description = "Corrupti eos est suscipit maiores nam nihil dignissimos nostrum.",
                            IsAvailable = true,
                            Name = "Limonade",
                            Price = 25.07465321505658400m
                        },
                        new
                        {
                            Id = 27,
                            Category = "Plat principal",
                            Description = "Qui unde qui quidem et laudantium totam beatae non id.",
                            IsAvailable = true,
                            Name = "Bavette de boeuf",
                            Price = 20.0792692571921600m
                        },
                        new
                        {
                            Id = 28,
                            Category = "Plat principal",
                            Description = "Qui dolores qui in rem et tempore.",
                            IsAvailable = true,
                            Name = "Burger de poulet",
                            Price = 19.19165011901484800m
                        },
                        new
                        {
                            Id = 29,
                            Category = "Plat principal",
                            Description = "Adipisci earum neque quia ut non praesentium recusandae voluptas.",
                            IsAvailable = true,
                            Name = "Burger de poulet",
                            Price = 25.90762123811878400m
                        },
                        new
                        {
                            Id = 30,
                            Category = "Entrée",
                            Description = "Velit est tenetur fugiat qui.",
                            IsAvailable = true,
                            Name = "Salade césar",
                            Price = 19.26060542128541600m
                        });
                });

            modelBuilder.Entity("TP2.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OrderTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TableId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TableId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TP2.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("TP2.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("GuestCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ReservationTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TableId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 9,
                            GuestCount = 4,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 16, 4, 50, 40, 921, DateTimeKind.Unspecified).AddTicks(3803), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Confirmée",
                            TableId = 13
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 40,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 4, 18, 28, 25, 352, DateTimeKind.Unspecified).AddTicks(9215), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Confirmée",
                            TableId = 3
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 1,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 11, 6, 18, 7, 502, DateTimeKind.Unspecified).AddTicks(5005), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 3
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 31,
                            GuestCount = 1,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 26, 0, 34, 29, 691, DateTimeKind.Unspecified).AddTicks(4504), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 1
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 35,
                            GuestCount = 4,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 22, 15, 24, 55, 656, DateTimeKind.Unspecified).AddTicks(2062), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 2
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 41,
                            GuestCount = 1,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 20, 23, 34, 8, 734, DateTimeKind.Unspecified).AddTicks(1829), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 17
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 4,
                            GuestCount = 6,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 23, 6, 52, 27, 225, DateTimeKind.Unspecified).AddTicks(3870), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Confirmée",
                            TableId = 2
                        },
                        new
                        {
                            Id = 8,
                            CustomerId = 17,
                            GuestCount = 6,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 12, 16, 33, 35, 189, DateTimeKind.Unspecified).AddTicks(4057), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 2
                        },
                        new
                        {
                            Id = 9,
                            CustomerId = 22,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 7, 9, 48, 45, 669, DateTimeKind.Unspecified).AddTicks(5226), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Confirmée",
                            TableId = 3
                        },
                        new
                        {
                            Id = 10,
                            CustomerId = 21,
                            GuestCount = 7,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 1, 7, 11, 20, 523, DateTimeKind.Unspecified).AddTicks(23), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Confirmée",
                            TableId = 3
                        },
                        new
                        {
                            Id = 11,
                            CustomerId = 14,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 31, 12, 1, 35, 422, DateTimeKind.Unspecified).AddTicks(8782), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 3
                        },
                        new
                        {
                            Id = 12,
                            CustomerId = 38,
                            GuestCount = 6,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 12, 9, 25, 5, 127, DateTimeKind.Unspecified).AddTicks(4383), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Confirmée",
                            TableId = 7
                        },
                        new
                        {
                            Id = 13,
                            CustomerId = 30,
                            GuestCount = 6,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 2, 17, 54, 35, 952, DateTimeKind.Unspecified).AddTicks(2202), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 2
                        },
                        new
                        {
                            Id = 14,
                            CustomerId = 36,
                            GuestCount = 5,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 23, 16, 46, 21, 598, DateTimeKind.Unspecified).AddTicks(8479), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Confirmée",
                            TableId = 2
                        },
                        new
                        {
                            Id = 15,
                            CustomerId = 43,
                            GuestCount = 5,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 24, 23, 45, 37, 485, DateTimeKind.Unspecified).AddTicks(3056), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Confirmée",
                            TableId = 3
                        },
                        new
                        {
                            Id = 16,
                            CustomerId = 33,
                            GuestCount = 6,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 5, 23, 2, 49, 367, DateTimeKind.Unspecified).AddTicks(9525), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 7
                        },
                        new
                        {
                            Id = 17,
                            CustomerId = 42,
                            GuestCount = 3,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 10, 20, 59, 30, 113, DateTimeKind.Unspecified).AddTicks(8565), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Confirmée",
                            TableId = 14
                        },
                        new
                        {
                            Id = 18,
                            CustomerId = 21,
                            GuestCount = 2,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 23, 4, 20, 31, 245, DateTimeKind.Unspecified).AddTicks(5787), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 13
                        },
                        new
                        {
                            Id = 19,
                            CustomerId = 21,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 30, 11, 41, 9, 670, DateTimeKind.Unspecified).AddTicks(4837), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 7
                        },
                        new
                        {
                            Id = 20,
                            CustomerId = 9,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 30, 20, 27, 35, 571, DateTimeKind.Unspecified).AddTicks(9167), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 3
                        },
                        new
                        {
                            Id = 21,
                            CustomerId = 36,
                            GuestCount = 5,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 27, 0, 48, 53, 466, DateTimeKind.Unspecified).AddTicks(857), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Confirmée",
                            TableId = 3
                        },
                        new
                        {
                            Id = 22,
                            CustomerId = 17,
                            GuestCount = 2,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 22, 15, 5, 24, 612, DateTimeKind.Unspecified).AddTicks(1451), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Confirmée",
                            TableId = 1
                        },
                        new
                        {
                            Id = 23,
                            CustomerId = 9,
                            GuestCount = 6,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 6, 10, 24, 43, 787, DateTimeKind.Unspecified).AddTicks(9326), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 2
                        },
                        new
                        {
                            Id = 24,
                            CustomerId = 22,
                            GuestCount = 2,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 21, 7, 11, 48, 467, DateTimeKind.Unspecified).AddTicks(5701), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 12
                        },
                        new
                        {
                            Id = 25,
                            CustomerId = 18,
                            GuestCount = 4,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 17, 2, 48, 27, 98, DateTimeKind.Unspecified).AddTicks(2310), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 13
                        },
                        new
                        {
                            Id = 26,
                            CustomerId = 19,
                            GuestCount = 2,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 11, 21, 47, 22, 343, DateTimeKind.Unspecified).AddTicks(3401), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Confirmée",
                            TableId = 3
                        },
                        new
                        {
                            Id = 27,
                            CustomerId = 9,
                            GuestCount = 6,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 23, 16, 39, 45, 187, DateTimeKind.Unspecified).AddTicks(6404), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 2
                        },
                        new
                        {
                            Id = 28,
                            CustomerId = 46,
                            GuestCount = 7,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 11, 7, 32, 15, 254, DateTimeKind.Unspecified).AddTicks(3585), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 3
                        },
                        new
                        {
                            Id = 29,
                            CustomerId = 29,
                            GuestCount = 6,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 15, 4, 59, 19, 963, DateTimeKind.Unspecified).AddTicks(7473), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 3
                        },
                        new
                        {
                            Id = 30,
                            CustomerId = 41,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 25, 7, 38, 17, 229, DateTimeKind.Unspecified).AddTicks(599), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 3
                        },
                        new
                        {
                            Id = 31,
                            CustomerId = 27,
                            GuestCount = 4,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 21, 21, 26, 41, 270, DateTimeKind.Unspecified).AddTicks(8114), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 3
                        },
                        new
                        {
                            Id = 32,
                            CustomerId = 40,
                            GuestCount = 6,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 29, 4, 43, 25, 27, DateTimeKind.Unspecified).AddTicks(4258), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 7
                        },
                        new
                        {
                            Id = 33,
                            CustomerId = 7,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 10, 2, 50, 24, 830, DateTimeKind.Unspecified).AddTicks(5234), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 3
                        },
                        new
                        {
                            Id = 34,
                            CustomerId = 44,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 19, 11, 3, 58, 301, DateTimeKind.Unspecified).AddTicks(6563), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 3
                        },
                        new
                        {
                            Id = 35,
                            CustomerId = 37,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 10, 20, 1, 26, 555, DateTimeKind.Unspecified).AddTicks(9243), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Confirmée",
                            TableId = 3
                        },
                        new
                        {
                            Id = 36,
                            CustomerId = 23,
                            GuestCount = 2,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 8, 1, 42, 30, 12, DateTimeKind.Unspecified).AddTicks(1488), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 3
                        },
                        new
                        {
                            Id = 37,
                            CustomerId = 9,
                            GuestCount = 5,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 23, 9, 44, 46, 192, DateTimeKind.Unspecified).AddTicks(5274), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 7
                        },
                        new
                        {
                            Id = 38,
                            CustomerId = 44,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 23, 12, 34, 8, 19, DateTimeKind.Unspecified).AddTicks(7313), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 3
                        },
                        new
                        {
                            Id = 39,
                            CustomerId = 3,
                            GuestCount = 4,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 8, 21, 41, 34, 643, DateTimeKind.Unspecified).AddTicks(9585), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 14
                        },
                        new
                        {
                            Id = 40,
                            CustomerId = 42,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 21, 12, 15, 11, 35, DateTimeKind.Unspecified).AddTicks(308), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Confirmée",
                            TableId = 3
                        },
                        new
                        {
                            Id = 41,
                            CustomerId = 6,
                            GuestCount = 3,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 18, 5, 7, 10, 532, DateTimeKind.Unspecified).AddTicks(4685), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 2
                        },
                        new
                        {
                            Id = 42,
                            CustomerId = 8,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 3, 8, 26, 53, 764, DateTimeKind.Unspecified).AddTicks(7204), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 3
                        },
                        new
                        {
                            Id = 43,
                            CustomerId = 18,
                            GuestCount = 7,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 13, 14, 28, 25, 562, DateTimeKind.Unspecified).AddTicks(1002), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 3
                        },
                        new
                        {
                            Id = 44,
                            CustomerId = 29,
                            GuestCount = 7,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 31, 15, 5, 50, 409, DateTimeKind.Unspecified).AddTicks(4302), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 7
                        },
                        new
                        {
                            Id = 45,
                            CustomerId = 43,
                            GuestCount = 1,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 3, 8, 13, 7, 157, DateTimeKind.Unspecified).AddTicks(4152), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 13
                        },
                        new
                        {
                            Id = 46,
                            CustomerId = 35,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 7, 16, 13, 47, 895, DateTimeKind.Unspecified).AddTicks(4227), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 3
                        },
                        new
                        {
                            Id = 47,
                            CustomerId = 43,
                            GuestCount = 2,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 20, 1, 19, 34, 20, DateTimeKind.Unspecified).AddTicks(7381), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 12
                        },
                        new
                        {
                            Id = 48,
                            CustomerId = 8,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 26, 1, 40, 6, 900, DateTimeKind.Unspecified).AddTicks(8349), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 3
                        },
                        new
                        {
                            Id = 49,
                            CustomerId = 17,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 8, 16, 26, 59, 20, DateTimeKind.Unspecified).AddTicks(3212), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 3
                        },
                        new
                        {
                            Id = 50,
                            CustomerId = 10,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 4, 23, 57, 33, 828, DateTimeKind.Unspecified).AddTicks(5538), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 3
                        },
                        new
                        {
                            Id = 51,
                            CustomerId = 22,
                            GuestCount = 4,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 25, 23, 18, 50, 914, DateTimeKind.Unspecified).AddTicks(4575), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 2
                        },
                        new
                        {
                            Id = 52,
                            CustomerId = 24,
                            GuestCount = 7,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 7, 12, 22, 25, 676, DateTimeKind.Unspecified).AddTicks(8094), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 3
                        },
                        new
                        {
                            Id = 53,
                            CustomerId = 4,
                            GuestCount = 5,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 7, 15, 59, 14, 852, DateTimeKind.Unspecified).AddTicks(6019), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Confirmée",
                            TableId = 2
                        },
                        new
                        {
                            Id = 54,
                            CustomerId = 48,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 21, 16, 15, 53, 197, DateTimeKind.Unspecified).AddTicks(5393), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 3
                        },
                        new
                        {
                            Id = 55,
                            CustomerId = 48,
                            GuestCount = 6,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 4, 3, 16, 36, 129, DateTimeKind.Unspecified).AddTicks(9877), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Confirmée",
                            TableId = 7
                        },
                        new
                        {
                            Id = 56,
                            CustomerId = 48,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 21, 18, 59, 23, 519, DateTimeKind.Unspecified).AddTicks(9508), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 7
                        },
                        new
                        {
                            Id = 57,
                            CustomerId = 43,
                            GuestCount = 6,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 31, 21, 57, 9, 714, DateTimeKind.Unspecified).AddTicks(2039), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Confirmée",
                            TableId = 2
                        },
                        new
                        {
                            Id = 58,
                            CustomerId = 9,
                            GuestCount = 5,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 28, 1, 14, 34, 185, DateTimeKind.Unspecified).AddTicks(7520), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 2
                        },
                        new
                        {
                            Id = 59,
                            CustomerId = 33,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 9, 23, 36, 38, 216, DateTimeKind.Unspecified).AddTicks(517), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 3
                        },
                        new
                        {
                            Id = 60,
                            CustomerId = 35,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 19, 9, 11, 28, 321, DateTimeKind.Unspecified).AddTicks(8100), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 3
                        },
                        new
                        {
                            Id = 61,
                            CustomerId = 29,
                            GuestCount = 2,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 14, 0, 17, 39, 495, DateTimeKind.Unspecified).AddTicks(2797), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 12
                        },
                        new
                        {
                            Id = 62,
                            CustomerId = 24,
                            GuestCount = 4,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 8, 12, 15, 44, 461, DateTimeKind.Unspecified).AddTicks(2425), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 7
                        },
                        new
                        {
                            Id = 63,
                            CustomerId = 32,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 23, 14, 17, 37, 578, DateTimeKind.Unspecified).AddTicks(5295), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 3
                        },
                        new
                        {
                            Id = 64,
                            CustomerId = 13,
                            GuestCount = 3,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 24, 5, 25, 3, 904, DateTimeKind.Unspecified).AddTicks(6796), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 11
                        },
                        new
                        {
                            Id = 65,
                            CustomerId = 24,
                            GuestCount = 4,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 10, 2, 54, 43, 572, DateTimeKind.Unspecified).AddTicks(7934), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 7
                        },
                        new
                        {
                            Id = 66,
                            CustomerId = 16,
                            GuestCount = 6,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 19, 1, 50, 6, 640, DateTimeKind.Unspecified).AddTicks(2898), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 2
                        },
                        new
                        {
                            Id = 67,
                            CustomerId = 24,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 21, 0, 1, 23, 729, DateTimeKind.Unspecified).AddTicks(2985), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 3
                        },
                        new
                        {
                            Id = 68,
                            CustomerId = 24,
                            GuestCount = 2,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 11, 9, 15, 39, 874, DateTimeKind.Unspecified).AddTicks(1371), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Confirmée",
                            TableId = 1
                        },
                        new
                        {
                            Id = 69,
                            CustomerId = 44,
                            GuestCount = 6,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 3, 2, 38, 30, 965, DateTimeKind.Unspecified).AddTicks(3547), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 2
                        },
                        new
                        {
                            Id = 70,
                            CustomerId = 28,
                            GuestCount = 2,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 21, 20, 6, 48, 71, DateTimeKind.Unspecified).AddTicks(9436), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 17
                        },
                        new
                        {
                            Id = 71,
                            CustomerId = 45,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 7, 1, 15, 37, 83, DateTimeKind.Unspecified).AddTicks(170), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 3
                        },
                        new
                        {
                            Id = 72,
                            CustomerId = 12,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 29, 19, 1, 55, 504, DateTimeKind.Unspecified).AddTicks(2401), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 3
                        },
                        new
                        {
                            Id = 73,
                            CustomerId = 33,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 3, 16, 21, 46, 950, DateTimeKind.Unspecified).AddTicks(5593), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 3
                        },
                        new
                        {
                            Id = 74,
                            CustomerId = 16,
                            GuestCount = 5,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 16, 11, 40, 4, 204, DateTimeKind.Unspecified).AddTicks(916), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Confirmée",
                            TableId = 7
                        },
                        new
                        {
                            Id = 75,
                            CustomerId = 43,
                            GuestCount = 6,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 23, 16, 44, 13, 497, DateTimeKind.Unspecified).AddTicks(3902), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 2
                        },
                        new
                        {
                            Id = 76,
                            CustomerId = 11,
                            GuestCount = 6,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 23, 0, 29, 35, 256, DateTimeKind.Unspecified).AddTicks(1533), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 2
                        },
                        new
                        {
                            Id = 77,
                            CustomerId = 4,
                            GuestCount = 7,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 14, 10, 14, 7, 567, DateTimeKind.Unspecified).AddTicks(420), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 3
                        },
                        new
                        {
                            Id = 78,
                            CustomerId = 34,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 26, 22, 28, 38, 631, DateTimeKind.Unspecified).AddTicks(2575), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Confirmée",
                            TableId = 3
                        },
                        new
                        {
                            Id = 79,
                            CustomerId = 43,
                            GuestCount = 6,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 12, 1, 49, 37, 714, DateTimeKind.Unspecified).AddTicks(8784), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 7
                        },
                        new
                        {
                            Id = 80,
                            CustomerId = 35,
                            GuestCount = 5,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 31, 9, 29, 21, 799, DateTimeKind.Unspecified).AddTicks(7940), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 2
                        },
                        new
                        {
                            Id = 81,
                            CustomerId = 11,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 15, 13, 46, 16, 842, DateTimeKind.Unspecified).AddTicks(5621), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 3
                        },
                        new
                        {
                            Id = 82,
                            CustomerId = 6,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 20, 20, 27, 43, 699, DateTimeKind.Unspecified).AddTicks(2514), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Confirmée",
                            TableId = 3
                        },
                        new
                        {
                            Id = 83,
                            CustomerId = 39,
                            GuestCount = 7,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 23, 15, 23, 43, 780, DateTimeKind.Unspecified).AddTicks(9573), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 7
                        },
                        new
                        {
                            Id = 84,
                            CustomerId = 26,
                            GuestCount = 2,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 4, 9, 56, 19, 911, DateTimeKind.Unspecified).AddTicks(341), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 1
                        },
                        new
                        {
                            Id = 85,
                            CustomerId = 20,
                            GuestCount = 2,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 22, 21, 3, 2, 900, DateTimeKind.Unspecified).AddTicks(3106), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Confirmée",
                            TableId = 5
                        },
                        new
                        {
                            Id = 86,
                            CustomerId = 42,
                            GuestCount = 1,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 14, 13, 59, 22, 451, DateTimeKind.Unspecified).AddTicks(553), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 11
                        },
                        new
                        {
                            Id = 87,
                            CustomerId = 30,
                            GuestCount = 3,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 27, 3, 6, 52, 835, DateTimeKind.Unspecified).AddTicks(8267), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 14
                        },
                        new
                        {
                            Id = 88,
                            CustomerId = 19,
                            GuestCount = 5,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 15, 22, 48, 48, 689, DateTimeKind.Unspecified).AddTicks(278), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 7
                        },
                        new
                        {
                            Id = 89,
                            CustomerId = 27,
                            GuestCount = 6,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 21, 6, 14, 53, 842, DateTimeKind.Unspecified).AddTicks(6376), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 2
                        },
                        new
                        {
                            Id = 90,
                            CustomerId = 6,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 27, 14, 39, 37, 129, DateTimeKind.Unspecified).AddTicks(7715), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 3
                        },
                        new
                        {
                            Id = 91,
                            CustomerId = 10,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 21, 16, 5, 10, 390, DateTimeKind.Unspecified).AddTicks(3638), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 3
                        },
                        new
                        {
                            Id = 92,
                            CustomerId = 4,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 11, 0, 21, 18, 64, DateTimeKind.Unspecified).AddTicks(4825), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 3
                        },
                        new
                        {
                            Id = 93,
                            CustomerId = 24,
                            GuestCount = 3,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 4, 13, 7, 24, 908, DateTimeKind.Unspecified).AddTicks(5590), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 1
                        },
                        new
                        {
                            Id = 94,
                            CustomerId = 16,
                            GuestCount = 4,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 17, 15, 28, 37, 343, DateTimeKind.Unspecified).AddTicks(5575), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Confirmée",
                            TableId = 18
                        },
                        new
                        {
                            Id = 95,
                            CustomerId = 14,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 22, 3, 59, 8, 110, DateTimeKind.Unspecified).AddTicks(7555), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "En attente",
                            TableId = 7
                        },
                        new
                        {
                            Id = 96,
                            CustomerId = 50,
                            GuestCount = 6,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 30, 15, 18, 59, 927, DateTimeKind.Unspecified).AddTicks(9806), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 7
                        },
                        new
                        {
                            Id = 97,
                            CustomerId = 13,
                            GuestCount = 8,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 10, 12, 23, 11, 866, DateTimeKind.Unspecified).AddTicks(5006), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 3
                        },
                        new
                        {
                            Id = 98,
                            CustomerId = 4,
                            GuestCount = 5,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 15, 19, 49, 5, 455, DateTimeKind.Unspecified).AddTicks(8198), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Annulée",
                            TableId = 3
                        },
                        new
                        {
                            Id = 99,
                            CustomerId = 14,
                            GuestCount = 2,
                            ReservationTime = new DateTimeOffset(new DateTime(2025, 1, 12, 19, 38, 49, 885, DateTimeKind.Unspecified).AddTicks(7124), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Confirmée",
                            TableId = 18
                        },
                        new
                        {
                            Id = 100,
                            CustomerId = 49,
                            GuestCount = 5,
                            ReservationTime = new DateTimeOffset(new DateTime(2024, 12, 9, 1, 12, 5, 493, DateTimeKind.Unspecified).AddTicks(3377), new TimeSpan(0, -5, 0, 0, 0)),
                            Status = "Confirmée",
                            TableId = 7
                        });
                });

            modelBuilder.Entity("TP2.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 4,
                            IsAvailable = true,
                            Location = "Privé",
                            Number = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 6,
                            IsAvailable = true,
                            Location = "Privé",
                            Number = 2
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 8,
                            IsAvailable = true,
                            Location = "Salle principale",
                            Number = 3
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 2,
                            IsAvailable = false,
                            Location = "Salle principale",
                            Number = 4
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 2,
                            IsAvailable = true,
                            Location = "Coin fenêtre",
                            Number = 5
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 2,
                            IsAvailable = false,
                            Location = "Salle principale",
                            Number = 6
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 8,
                            IsAvailable = true,
                            Location = "Terrasse",
                            Number = 7
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 2,
                            IsAvailable = false,
                            Location = "Terrasse",
                            Number = 8
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 2,
                            IsAvailable = true,
                            Location = "Privé",
                            Number = 9
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 2,
                            IsAvailable = true,
                            Location = "Terrasse",
                            Number = 10
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 4,
                            IsAvailable = true,
                            Location = "Coin fenêtre",
                            Number = 11
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 2,
                            IsAvailable = true,
                            Location = "Salle principale",
                            Number = 12
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 4,
                            IsAvailable = true,
                            Location = "Salle principale",
                            Number = 13
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 4,
                            IsAvailable = true,
                            Location = "Salle principale",
                            Number = 14
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 4,
                            IsAvailable = false,
                            Location = "Terrasse",
                            Number = 15
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 4,
                            IsAvailable = false,
                            Location = "Coin fenêtre",
                            Number = 16
                        },
                        new
                        {
                            Id = 17,
                            Capacity = 2,
                            IsAvailable = true,
                            Location = "Salle principale",
                            Number = 17
                        },
                        new
                        {
                            Id = 18,
                            Capacity = 4,
                            IsAvailable = true,
                            Location = "Privé",
                            Number = 18
                        },
                        new
                        {
                            Id = 19,
                            Capacity = 2,
                            IsAvailable = false,
                            Location = "Salle principale",
                            Number = 19
                        },
                        new
                        {
                            Id = 20,
                            Capacity = 8,
                            IsAvailable = false,
                            Location = "Salle principale",
                            Number = 20
                        });
                });

            modelBuilder.Entity("TP2.Models.Order", b =>
                {
                    b.HasOne("TP2.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP2.Models.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId");

                    b.Navigation("Customer");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("TP2.Models.OrderItem", b =>
                {
                    b.HasOne("TP2.Models.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP2.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TP2.Models.Reservation", b =>
                {
                    b.HasOne("TP2.Models.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP2.Models.Table", "Table")
                        .WithMany("Reservations")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("TP2.Models.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("TP2.Models.MenuItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("TP2.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TP2.Models.Table", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
