// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP2.Data;

#nullable disable

namespace TP2.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20250304031636_ClientMigration")]
    partial class ClientMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TP2.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 11, 29, 19, 4, 33, 702, DateTimeKind.Unspecified).AddTicks(544), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Annabelle_Bernier@hotmail.com",
                            FirstName = "Annabelle",
                            LastName = "Bernier"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 6, 21, 16, 38, 29, 953, DateTimeKind.Unspecified).AddTicks(454), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Cassidy.Rippin@gmail.com",
                            FirstName = "Cassidy",
                            LastName = "Rippin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 12, 12, 3, 54, 28, 41, DateTimeKind.Unspecified).AddTicks(6247), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Crystel.Aufderhar88@gmail.com",
                            FirstName = "Crystel",
                            LastName = "Aufderhar"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 8, 31, 10, 53, 27, 324, DateTimeKind.Unspecified).AddTicks(2698), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Flossie_Braun@yahoo.com",
                            FirstName = "Flossie",
                            LastName = "Braun"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 9, 4, 51, 18, 414, DateTimeKind.Unspecified).AddTicks(8402), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Liliane.Reynolds@hotmail.com",
                            FirstName = "Liliane",
                            LastName = "Reynolds"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 2, 1, 22, 39, 12, 250, DateTimeKind.Unspecified).AddTicks(5127), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Cortez77@yahoo.com",
                            FirstName = "Cortez",
                            LastName = "Larson"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 14, 14, 13, 40, 346, DateTimeKind.Unspecified).AddTicks(1811), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Jayson.King26@yahoo.com",
                            FirstName = "Jayson",
                            LastName = "King"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 23, 20, 0, 38, 131, DateTimeKind.Unspecified).AddTicks(8860), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Lorine.Grimes85@yahoo.com",
                            FirstName = "Lorine",
                            LastName = "Grimes"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 18, 8, 58, 37, 408, DateTimeKind.Unspecified).AddTicks(2281), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Levi53@yahoo.com",
                            FirstName = "Levi",
                            LastName = "Kiehn"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 6, 4, 9, 30, 7, 485, DateTimeKind.Unspecified).AddTicks(7662), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Annamae41@gmail.com",
                            FirstName = "Annamae",
                            LastName = "Waters"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 6, 13, 5, 51, 25, 25, DateTimeKind.Unspecified).AddTicks(9775), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Adriel_Schuppe76@gmail.com",
                            FirstName = "Adriel",
                            LastName = "Schuppe"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 19, 9, 38, 268, DateTimeKind.Unspecified).AddTicks(952), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Myrna_Rath@yahoo.com",
                            FirstName = "Myrna",
                            LastName = "Rath"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 12, 19, 0, 18, 12, 59, DateTimeKind.Unspecified).AddTicks(3356), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Destiny25@gmail.com",
                            FirstName = "Destiny",
                            LastName = "Blanda"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 2, 8, 15, 3, 54, 329, DateTimeKind.Unspecified).AddTicks(3517), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Kiana76@yahoo.com",
                            FirstName = "Kiana",
                            LastName = "Little"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 6, 23, 8, 14, 33, 976, DateTimeKind.Unspecified).AddTicks(9403), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Jackie_Rau27@gmail.com",
                            FirstName = "Jackie",
                            LastName = "Rau"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 7, 5, 14, 44, 38, 885, DateTimeKind.Unspecified).AddTicks(1255), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Eldora_Brown@gmail.com",
                            FirstName = "Eldora",
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 4, 5, 16, 35, 14, 602, DateTimeKind.Unspecified).AddTicks(4654), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Loyce93@hotmail.com",
                            FirstName = "Loyce",
                            LastName = "Bogan"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 30, 4, 2, 27, 597, DateTimeKind.Unspecified).AddTicks(4628), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Annalise63@yahoo.com",
                            FirstName = "Annalise",
                            LastName = "Stanton"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 11, 1, 4, 31, 1, 541, DateTimeKind.Unspecified).AddTicks(940), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Lukas_Walsh41@gmail.com",
                            FirstName = "Lukas",
                            LastName = "Walsh"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 11, 20, 20, 58, 4, 591, DateTimeKind.Unspecified).AddTicks(9707), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Demarcus30@gmail.com",
                            FirstName = "Demarcus",
                            LastName = "Stanton"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 2, 2, 16, 44, 7, 695, DateTimeKind.Unspecified).AddTicks(8928), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Carmel_Cummings@hotmail.com",
                            FirstName = "Carmel",
                            LastName = "Cummings"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 11, 5, 9, 9, 58, 721, DateTimeKind.Unspecified).AddTicks(8534), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Leora_Koch@hotmail.com",
                            FirstName = "Leora",
                            LastName = "Koch"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 7, 10, 8, 20, 38, 470, DateTimeKind.Unspecified).AddTicks(1153), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Hilma.Orn7@hotmail.com",
                            FirstName = "Hilma",
                            LastName = "Orn"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 7, 13, 20, 5, 28, 801, DateTimeKind.Unspecified).AddTicks(1605), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Henriette.Weimann@hotmail.com",
                            FirstName = "Henriette",
                            LastName = "Weimann"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 6, 13, 2, 13, 44, 131, DateTimeKind.Unspecified).AddTicks(6967), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Emerson_Spencer@hotmail.com",
                            FirstName = "Emerson",
                            LastName = "Spencer"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 7, 31, 9, 33, 3, 445, DateTimeKind.Unspecified).AddTicks(5844), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Alexandro.Lakin8@gmail.com",
                            FirstName = "Alexandro",
                            LastName = "Lakin"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 25, 20, 55, 3, 41, DateTimeKind.Unspecified).AddTicks(4366), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Rod_Goodwin@gmail.com",
                            FirstName = "Rod",
                            LastName = "Goodwin"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 5, 21, 40, 17, 249, DateTimeKind.Unspecified).AddTicks(4879), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Heber_Bogan54@yahoo.com",
                            FirstName = "Heber",
                            LastName = "Bogan"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 11, 22, 2, 52, 34, 51, DateTimeKind.Unspecified).AddTicks(4681), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Clinton.Morar82@hotmail.com",
                            FirstName = "Clinton",
                            LastName = "Morar"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 1, 22, 12, 2, 903, DateTimeKind.Unspecified).AddTicks(8879), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Susie.Fahey28@gmail.com",
                            FirstName = "Susie",
                            LastName = "Fahey"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 5, 8, 18, 14, 349, DateTimeKind.Unspecified).AddTicks(1106), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Nora_Funk61@gmail.com",
                            FirstName = "Nora",
                            LastName = "Funk"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 2, 12, 10, 20, 12, 724, DateTimeKind.Unspecified).AddTicks(9489), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Dayne.Cummerata@yahoo.com",
                            FirstName = "Dayne",
                            LastName = "Cummerata"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 11, 25, 17, 58, 37, 693, DateTimeKind.Unspecified).AddTicks(2547), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Nikita85@hotmail.com",
                            FirstName = "Nikita",
                            LastName = "Hettinger"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 8, 11, 8, 48, 16, 143, DateTimeKind.Unspecified).AddTicks(3618), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Stanton.Cummerata@yahoo.com",
                            FirstName = "Stanton",
                            LastName = "Cummerata"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 3, 17, 20, 14, 25, 844, DateTimeKind.Unspecified).AddTicks(1540), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Christopher.Gottlieb@yahoo.com",
                            FirstName = "Christopher",
                            LastName = "Gottlieb"
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 1, 6, 28, 0, 311, DateTimeKind.Unspecified).AddTicks(8784), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Isabella_Kutch@gmail.com",
                            FirstName = "Isabella",
                            LastName = "Kutch"
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 7, 14, 8, 23, 31, 866, DateTimeKind.Unspecified).AddTicks(2379), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Rubie95@hotmail.com",
                            FirstName = "Rubie",
                            LastName = "Wisozk"
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 11, 22, 3, 6, 201, DateTimeKind.Unspecified).AddTicks(2667), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Jayda.Koelpin54@gmail.com",
                            FirstName = "Jayda",
                            LastName = "Koelpin"
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 6, 6, 4, 29, 23, 226, DateTimeKind.Unspecified).AddTicks(7610), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Annie.Batz@gmail.com",
                            FirstName = "Annie",
                            LastName = "Batz"
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 18, 14, 27, 3, 235, DateTimeKind.Unspecified).AddTicks(4496), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Lizeth.Osinski8@yahoo.com",
                            FirstName = "Lizeth",
                            LastName = "Osinski"
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 3, 8, 12, 24, 2, 868, DateTimeKind.Unspecified).AddTicks(747), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Anabel_Gorczany@hotmail.com",
                            FirstName = "Anabel",
                            LastName = "Gorczany"
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 4, 17, 15, 16, 52, 644, DateTimeKind.Unspecified).AddTicks(8649), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Justine_Prosacco89@gmail.com",
                            FirstName = "Justine",
                            LastName = "Prosacco"
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 4, 24, 10, 50, 41, 913, DateTimeKind.Unspecified).AddTicks(8211), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Vivienne.Considine@hotmail.com",
                            FirstName = "Vivienne",
                            LastName = "Considine"
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 3, 14, 4, 56, 57, 754, DateTimeKind.Unspecified).AddTicks(4200), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Alvina17@gmail.com",
                            FirstName = "Alvina",
                            LastName = "Harvey"
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 10, 4, 0, 20, 893, DateTimeKind.Unspecified).AddTicks(3018), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Willy.Hahn@gmail.com",
                            FirstName = "Willy",
                            LastName = "Hahn"
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 8, 3, 17, 48, 35, 45, DateTimeKind.Unspecified).AddTicks(4671), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Laisha.Volkman@gmail.com",
                            FirstName = "Laisha",
                            LastName = "Volkman"
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 11, 30, 4, 4, 28, 170, DateTimeKind.Unspecified).AddTicks(8985), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Jimmie57@hotmail.com",
                            FirstName = "Jimmie",
                            LastName = "Shanahan"
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 7, 21, 48, 40, 203, DateTimeKind.Unspecified).AddTicks(1069), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Camille.Hudson48@yahoo.com",
                            FirstName = "Camille",
                            LastName = "Hudson"
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 2, 6, 19, 48, 19, 678, DateTimeKind.Unspecified).AddTicks(355), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Viva29@gmail.com",
                            FirstName = "Viva",
                            LastName = "Haag"
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 3, 18, 13, 30, 37, 251, DateTimeKind.Unspecified).AddTicks(8021), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "Claire_Schaden32@yahoo.com",
                            FirstName = "Claire",
                            LastName = "Schaden"
                        });
                });

            modelBuilder.Entity("TP2.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("TP2.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OrderTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TableId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TableId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TP2.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("TP2.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("GuestCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ReservationTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TableId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("TP2.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("TP2.Models.Order", b =>
                {
                    b.HasOne("TP2.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP2.Models.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId");

                    b.Navigation("Customer");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("TP2.Models.OrderItem", b =>
                {
                    b.HasOne("TP2.Models.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP2.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TP2.Models.Reservation", b =>
                {
                    b.HasOne("TP2.Models.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP2.Models.Table", "Table")
                        .WithMany("Reservations")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("TP2.Models.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("TP2.Models.MenuItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("TP2.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TP2.Models.Table", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
